### ISSUE TITLE
Prevent panic on invalid interface number

### ISSUE THREAD

**Issue by linkmauve** [jiegec/usbip#2]
At https://github.com/jiegec/usbip/blob/master/src/device.rs#L349, `setup_packet.index` is sometimes (much) larger than the number of interfaces, I got 514, 1284, 264, 520, 1034 and 1290 for instance on a device with only 12 interfaces.

Since all of them seem to be in range modulo 256, I could add such a modulo but I’d prefer someone accustomed to USB to verify that this is indeed the correct fix.

The modulo otherwise fixes this panic:
```rust
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 12 but the index is 514', src/device.rs:349:37
```

**Comment by jiegec** [comment]
Oh, that's weird.

**Comment by jiegec** [comment]
Yes, you are right:

![image](https://user-images.githubusercontent.com/6127678/116168526-2de4b280-a735-11eb-9806-0d3ab12fec9c.png)

**Comment by linkmauve** [comment]
This indeed fixes the issue, thanks!
