### ISSUE TITLE
Access to URB `transfer_buffer_length` in `handle_urb`

### ISSUE THREAD

**Issue by h7x4** [jiegec/usbip#24]
I'm trying to replay USB requests on a remote machine. There's a bit of a problematic API for `handle_urb`, where it seems to be missing a variable that's supposed to tell how large the data buffer is. The setup packets `wLength` appear to only be for control requests.

Maybe the `transfer_buffer_length` from [the urb struct](https://docs.kernel.org/driver-api/usb/URB.html#the-urb-structure) should be included as an argument to both device and interface `handle_urb`?

This is the field I'm trying to access, for an interface bulk in request

![image](https://github.com/jiegec/usbip/assets/14929991/75a5480d-e79a-4940-aeef-06a1a2019328)

**Comment by jiegec** [comment]
I am not expert in USB, but it seems reasonable. You could create a pull request to pass the length from lib.rs:handler() to handle_urb().
