### ISSUE TITLE
Server wrongly assumes devices are no longer used after unlink command

### ISSUE THREAD

**Issue by florg-32** [jiegec/usbip#39]
In the current implementation, the server removes a USB device from its `used_device` list when it receives `USBIP_CMD_UNLINK`. 

This however leads to issues when multiple URBs are unlinked (wrongly triggers `usbip_ret_unlink_fail`) or when attempting to submit an URB afterwards (panics on `current_import_device.unwrap()`). Looking at the [USB/IP protocol](https://docs.kernel.org/usb/usbip_protocol.html) (3rd diagram) both things should be possible.

**Comment by h7x4** [comment]
Hello, thank you for the detailed bug report!

While looking into this, I realize that I have completely misunderstood what `USBIP_CMD_UNLINK` was supposed to do, as I thought it was a request for graceful shutdown of the connection.

I'll hopefully be able to have a closer look at it in the next few days.
